baseurl:
url: http://localhost
#url-slash: url: http://localhost/
#url-shop: url: http://localhost/shop/
#url-form: https://mail.supportdesk.shop/form.php
#zendesk: https://supportdesknu.zendesk.com/

# Site settings
name: SupportDesk BV
title: Support voor Magento en Joomla
sufix: Support voor Magento en Joomla
domain-name: SupportDesk
robots: NOINDEX,NOFOLLOW
email: info@supportdesk.nu
email-support: support@supportdesk.nu
description: "Magento en Joomla support nodig?"
google_analytics: //UA-31123279-1//unset
fb_app_id: //197353897051595//unset
logo: /img/logos/supportdesk-logo.svg
logo-jpg: /img/logos/supportdesk-logo.jpg
logo-tumb: /img/logos/supportdesk-logo-tumb.jpg
tel: 020-3375961
hours: 09.00-18.00
paginate: 5
paginate_path: "/blog/page:num"
defaults:
  - scope:
      path: "blog/page"
    values:
      sitemap: false

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/supportdesknu
  - title: twitter
    url: https://twitter.com/supportdesknu
  - title: linkedin
    url: https://www.linkedin.com/company/supportdesknu

# Postal address (add as many lines as necessary)
address-amsterdam:
  - line: Hogehilweg 19
  - line: 1101 CB, Amsterdam

address-rotterdam:
  - line: Marconistraat 16
  - line: 3029 AK Rotterdam

review-rate: 9.4
review-scale: 10
review-total: 161

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: compressed

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-sitemap
  - html-proofer
