url: https://mage-academy.training
#baseurl: /agency-jekyll-theme/

# Site settings
title: Magento Training Academy
email: training@supportdesk.nu
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:
- name: Ray Bogman
  pic: 1
  position: CTO / Magento Doctor
  social:
    - title: twitter
      url: https://twitter.com/raybogman
    - title: linkedin
      url: https://nl.linkedin.com/in/raybogman

- name: Vladimir Kerkhoff
  pic: 2
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

- name: Erik van Rijn
  pic: 3
  position: Lead Developer
  social:
    - title: twitter
      url: #
    - title: linkedin
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
