url: https://supportdesk.shop/
url-non: https://supportdesk.shop
url-shop: https://www.supportdesk.nu/shop/
url-form: https://mail.supportdesk.shop/form.php
zendesk: https://supportdesknu.zendesk.com/

# Site settings
name: SupportDesk BV
title: Support voor Magento en Joomla
sufix: Support voor Magento en Joomla
domain-name: SupportDesk
robots: NOINDEX,NOFOLLOW
email: info@supportdesk.nu
email-support: support@supportdesk.nu
description: "Magento en Joomla support nodig?"
google_analytics: //UA-31123279-1//unset
fb_app_id: //717157511826431/unset
logo: /img/logos/supportdesk-logo.svg
tel: 020-3375961
hours: 09.00-18.00
paginate: 5
paginate_path: "/blog/page:num"

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/supportdesknu
  - title: twitter
    url: https://twitter.com/supportdesknu
  - title: linkedin
    url: https://www.linkedin.com/company/supportdesknu

# Postal address (add as many lines as necessary)
address:
  - line: Hogehilweg 19
  - line: 1101 CB, Amsterdam

review-rate: 9.4
review-scale: 10
review-total: 161

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: compressed

sitemap:
  lastmod: 2016-09-26
  priority: 0.7
  changefreq: 'monthly'
  exclude: 'yes'

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-email-protect
  - jekyll-sitemap
  - html-proofer
