url: https://mage-academy.training/

# Site settings
title: Magento Training Academy
name: Ray Bogman
robots: INDEX,FOLLOW
email: training@supportdesk.nu
description: "Magento 2 Training Academy. Learn Magento 2 now, sign up and get started with Magento 2"
google_analytics: UA-56035124-2

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: youtube
    url: https://www.youtube.com/channel/UCL5iTukHCFPemED2kpf56sg
  - title: twitter
    url: https://twitter.com/rapidonu
  - title: linkedin
    url: https://www.linkedin.com/company/rapido-internet-solutions-b-v-

# Postal address (add as many lines as necessary)
address:
  - line: De Ruijterkade 139
  - line: 1188 DP, Amsterdam

# Build settings
markdown: kramdown
permalink: pretty

sass:
    style: compressed

sitemap:
  lastmod: 2016-09-26
  priority: 0.7
  changefreq: 'monthly'
  exclude: 'yes'

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-seo-tag
