version: '2'
services:
    jekyll:
          container_name: jekyll
          restart: always
          image: jekyll/jekyll:pages
          hostname: jekyll
          command: jekyll build --watch --incremental --profile
#          command: jekyll build --watch --incremental --profile --config _config.yml,_config-dev.yml
          ports:
            - 4000:4000
          volumes:
            - .:/srv/jekyll
    nginx:
          container_name: nginx
          restart: always
          image: nginx
          hostname: nginx
          ports:
            - 80:80
          volumes:
            - ./_site:/usr/share/nginx/html

#    db:
#          container_name: mysql
#          restart: always
#          image: mysql:5.6.33
#          volumes:
#              - $PWD/mysql:/var/lib/mysql
#              - $PWD:/root
#          environment:
#              MYSQL_ROOT_PASSWORD: password123
