- name: Magento 2 Merchant
  id: 1
  url: magento-2-merchant
  pic: magento-2-merchant
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Webmaster
  id: 2
  url: magento-2-webmaster
  pic: magento-2-webmaster
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Developer
  id: 3
  url: magento-2-developer
  pic: magento-2-developer
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Theming
  id: 4
  url: magento-2-theming
  pic: magento-2-theming
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Security
  id: 5
  url: magento-2-security
  pic: magento-2-security
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Performance
  id: 6
  url: magento-2-performance
  pic: magento-2-performance
  title-submenu: Training services
  height: 190
  width: 297
