- name: Magento 2 Merchant
  url: magento-2-merchant
  pic: magento-2-merchant
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Webmaster
  url: magento-2-webmaster
  pic: magento-2-webmaster
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Developer
  url: magento-2-developer
  pic: magento-2-developer
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Theming
  url: magento-2-theming
  pic: magento-2-theming
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Security
  url: magento-2-security
  pic: magento-2-security
  title-submenu: Training services
  height: 190
  width: 297

- name: Magento 2 Performance
  url: magento-2-performance
  pic: magento-2-performance
  title-submenu: Training services
  height: 190
  width: 297
