---
layout: 2column
title: SupportDesk op Meet Magento 2013
url: supportdesk-op-meet-magento-2013
description: Tal van nationale en internationale sprekers leveren een bijdrage met
  praktijkvoorbeelden, technische sessies, workshops en ronde tafel sessies. Ook SupportDesk
  zal op dit evenement aanwezig zijn, als sponsor en spreker.
image: supportdesk-op-meet-magento-2013
authorimage: Ray Bogman
authorname: Ray Bogman
datePublished: 2013-05-08 09:59:00.000000000 +00:00
dateModified: 2017-05-13 13:11:06.000000000 +00:00
intro: Tal van nationale en internationale sprekers leveren een bijdrage met praktijkvoorbeelden,
  technische sessies, workshops en ronde tafel sessies. Ook SupportDesk zal op dit
  evenement aanwezig zijn, als sponsor en spreker.
hits: 1702
nav: Blog
---
<p><a href="http://www.meet-magento.nl/" target="_blank" title="Ga naar Meet Magento "><img src="images/nieuws/mm13header.jpg" alt="mm13header" style="float: left; margin: 0px 0px 15px;" height="110" width="500" /></a><br style="clear: both;" />Dit jaar strijkt <a href="http://www.meet-magento.nl/" target="_blank" title="Meet Magento 2013"><strong>Meet Magento</strong></a> voor de vierde keer neer in het Gelderse Ede en wel in Hotel/Theater De Reehorst, een prachtige locatie in het midden van het land, op woensdag 29 mei en donderdag 30 mei.</p>
<p>Tal van nationale en internationale sprekers leveren een bijdrage met praktijkvoorbeelden, technische sessies, workshops en ronde tafel sessies. Ook <strong>SupportDesk</strong> zal op dit evenement aanwezig zijn, als sponsor en spreker.</p>
<p>Lees hier meer over de <a href="http://www.meet-magento.nl/locatie/" target="_blank" title="Locatie Meet Magento 2013">locatie </a>en het <a href="http://www.meet-magento.nl/programma/" target="_blank" title="Programma Meet Magento 2013">programma</a>.</p>
<h3>Oprichters Magento komen naar Nederland!</h3>
<p>Tijdens de allereerste Meet Magento in Europa op 27 januari 2009 waren zij er beiden bij. Toen was de software net gereleased maar de aandacht voor het systeem was al enorm door de unieke combinatie van open source en het scala aan features dat vergelijkbaar was met de grote commerciële systemen in die tijd.</p>
<p>Eind deze maand op 30 mei, tijdens de 5e editie van Meet Magento staan beide oprichters van Magento weer op het podium: <strong>Roy Rubin</strong> en <strong>Yoav Kutner</strong>.</p>
<p><img src="images/nieuws/royruben.jpg" alt="royruben" style="float: left; margin: 0 20px 10px 0;" height="80" width="80" />Tijdens de conferentie zal <a href="http://www.meet-magento.nl/speaker/roy-rubin/" target="_blank" title="Roy Rubin">Roy Rubin</a>, nu VP en COO bij eBay op 30 mei de opening keynote verzorgen. Roy houdt zich bezig met de algemene strategie van Magento als bedrijf met focus op het helpen van klanten en partners door het Magento platform. Hij overziet ook Magento’s trainingen, marketing, sales en support. Roy zal tijdens zijn keynote een overzicht geven van alle ontwikkelingen binnen Magento Inc. en eBay. Hij kijkt terug op het afgelopen jaar en kijkt vooruit naar de ontwikkelingen die we de komende tijd kunnen verwachten.</p>
<p><img src="images/nieuws/yoavkutner.jpg" alt="yoavkutner" style="float: right; margin: 0 0 10px 20px;" height="80" width="80" />Ook <a href="http://www.meet-magento.nl/speaker/yoav-kutner-jary-carter/" target="_blank" title="Yoav Kutner">Yoav Kutner</a> behoeft in de Magento community eigenlijk geen introductie meer. Yoav is met Roy mede oprichter van Magento en als voormalig CTO de grondlegger van de Magento software. Samen met Jary Cartner (voormalig Vice President bij Magento) is hij vorig jaar vertrokken bij Magento om zich te richten op een nieuw bedrijf (<a href="http://magecore.com/" target="_blank" title="Magecore">Magecore</a>) en een nieuw product (<a href="http://www.orocrm.com/" target="_blank" title="OroCRM">OroCRM</a>). Als eerste ter wereld zullen de bezoekers tijdens Meet Magento 2013 kennis kunnen maken met het systeem via een demo van het systeem door Yoav en Jary.</p>
<h3>Meet en Greet Supportdesk 29 mei</h3>
<p><a href="index.php?option=com_content&amp;view=article&amp;id=88:supportdesk-op-meet-magento-2013&amp;catid=29:blog&amp;Itemid=121" target="_self"><img src="images/nieuws/mm13borrel.jpg" alt="mm13borrel" style="float: left; margin: 0px 20px 10px 0px;" height="135" width="161" /></a>Op woensdag 29 mei zal Guido Jansen een introductiesessie verzorgen. Deze 3 uur durende sessie is bedoeld voor mensen die willen starten met Magento of net zijn begonnen. Lees hier meer over deze <a href="http://www.meet-magento.nl/magento-introductiesessie/%20" target="_blank" title="Meet Magento Introductiesessie">introductiesessie</a>.</p>
<p>Die avond, vanaf 19 uur zal er een Pre-Party zijn. Dit is een netwerkborrel voorafgaand aan de congresdag op 30 mei. Bestel hier de <a href="https://magento.paydro.net/" target="_blank" title="Meet Magento entree kaarten"> Meet Magento entree kaarten</a>.</p>
<p>Ben je erbij? Stuur even een bericht via ons <a href="http://www.supportdesk.nu/contact" target="_blank" title="Supportdesk contactformulier ">contactformulier </a>om te laten weten dat je langskomt!</p>
<h3>SupportDesk als Sponsor en Spreker op 30 mei</h3>
<p><a href="http://www.supportdesk.nu/magento-support/magento-apk" target="_blank" title="Meer informatie over Magento APK"><img src="images/nieuws/mm13apk.jpg" alt="mm13apk" style="float: right; margin: 0px 0px 20px 20px;" height="125" width="188" /></a>Graag zien we je (uiteraard helemaal fris na de borrel van de vorige avond) op onze stand langskomen. Je kan zelfs een <a href="index.php?option=com_content&amp;view=article&amp;id=71:magento-apk&amp;catid=9:magento&amp;Itemid=328" title="SupportDesk Magento APK">Magento APK</a> winnen. Het enige wat je daarvoor hoeft te doen is je visitekaartje bij ons achter te laten. Hiermee maak je kans op een Magento APK t.w.v. 250 euro en je wordt in de toekomst op de hoogte gehouden van alle nieuwtjes rondom Magento en Joomla! Er worden op het einde van de dag 5 <a href="index.php?option=com_content&amp;view=article&amp;id=71:magento-apk&amp;catid=9:magento&amp;Itemid=328" title="SupportDesk Magento APK">Magento APK</a>'s verloot.&nbsp;</p>
<h3>Spreker Richard &amp; Ray: de impact van Radio/TV commercials op je webshop</h3>
<p><img src="images/nieuws/mm13rr.jpg" alt="mm13rr" style="float: left; margin: 0 20px 0 0;" height="99" width="101" /><a href="over-ons/1-ray-bogman" title="Ray Bogman">Ray</a> heeft de afgelopen 5 jaar elk jaar als spreker op Meet Magento gestaan en Richard heeft in 2011 gesproken over de combinatie tussen Magento, Joomla (MageBridge) en Mobile. Inmiddels hebben ze een hoop interessante dingen meegemaakt en willen deze ervaringen graag met je delen.</p>
<p>De case gaat over <a href="http://www.supportdesk.nu/case-study/66-magento-cluster-condoom-anoniem-zon-zee-zuipen" target="_blank" title="Case study: de impact van Radio/TV commercials op je webshop">de impact van Radio/TV commercials op je webshop</a></p>
<p>Lees meer over <a href="http://www.meet-magento.nl/speaker/richard-spooren/" target="_blank" title="De case die Richard &amp;amp; Ray gaan bespreken op Meet Magento 2013">de case die Richard &amp; Ray gaan bespreken op deze pagina</a>. Tijdens deze sessie zullen ze vertellen over de valkuilen, de learnings, de benodigde infrastructuur en wat het nu allemaal uiteindelijk heeft opgeleverd voor de business.</p>
<h2>Win Meet Magento entree kaarten!!<a href="https://www.facebook.com/supportdesk.nu?ref=ts&amp;fref=ts" target="_blank" title="Like ons op Facebook"><img src="images/nieuws/winmm13entreekaarten.png" alt="winmm13entreekaarten" style="float: right;" height="245" width="180" /></a></h2>
<p>And last but not least...We hebben een aantal kaartjes (t.w.v. 140 euro per stuk) weg te geven en jij kan deze winnen! Like onze <a href="https://www.facebook.com/supportdesk.nu?ref=ts&amp;fref=ts" target="_blank" title="SupportDesk Facebook pagina">SupportDesk Facebook pagina</a> of <a href="https://twitter.com/supportdesknu" target="_blank" title="Follow onze SupportDesk Twitter">Follow onze SupportDesk Twitter</a> pagina. Let op: Deze entree kaartjes zijn bestemd voor webwinkeliers.&nbsp;&nbsp;</p>
<p>Wie zich vanaf vandaag tot en met 15 mei inschrijft maakt kans op deze kaarten.&nbsp;</p>
<p>&nbsp;</p>
<p>{snippet meer info}</p>
<p>{snippet sannepeters}</p>
