---
layout: 2column
title: Banken nog niet klaar voor mobile website checkout
url: banken-nog-niet-klaar-voor-mobile-website-checkout
description: Nederlandse Banken nog niet klaar voor mobile website checkout, ING,
  ABN AMRO en KNAB komen goed uit de test.
image: banken-nog-niet-klaar-voor-mobile-website-checkout
authorimage: Ray Bogman
authorname: Ray Bogman
datePublished: 2013-08-26 13:15:00.000000000 +00:00
dateModified: 2013-08-27 12:56:29.000000000 +00:00
intro: Nederlandse Banken nog niet klaar voor mobile website checkout, ING, ABN AMRO
  en KNAB komen goed uit de test.
hits: 2631
nav: Blog
---
<p>Tijdens een recent onderzoek is gebleken dat 7 van de 10 Banken geen klantvriendelijk webpagina hebben tijdens de checkout. De overige 3 banken boden de klant een iDEAL betaal pagina die zeer klantvriendelijk was en het checkout process vereenvoudigde.</p>
<h3>ING de grote winnaar</h3>
<p>De <strong>ING bank</strong> was de enige in het onderzoek die met kop en schouder boven iedereen uit stak. De gebruikersvriendelijkheid, overduidelijk kleur gebruik maakte alles zeer overzichtelijk. <strong>ABN AMRO</strong> en <strong>KNAB</strong> waren de overige banken die duidelijk die nieuwe webtechnieken zoals <strong>responsive design</strong> duidelijk op de juiste manier hebben toegepast. Alle 3 de banken maken standaard &nbsp;gebruik van een <strong>responsive layout</strong> in hun code.</p>
<p>De <strong>Rabobank</strong>, <strong>SNS Bank</strong>, <strong>Friesland Bank</strong>, <strong>ASN Bank</strong>, <strong>SNS Regio Bank</strong>, <strong>Triodios Bank</strong> en <strong>Van Lanschot Bankiers&nbsp;</strong>maakte standaard geen gebruik van een mobile variant van hun betaal pagina. In sommige gevallen was het niet eens mogelijk om op een <strong>Iphone</strong> of <strong>Andriod</strong> de bestelling te annuleren vanwege een popup scherm welke op een mobile browser maar amper zichtbaar is.</p>
<h3>Magento Mobile Checkout</h3>
<p><a style="float: right;" data-lightbox="width:640;height:1820;" href="images/nieuws/mobile-ca.png" title="Mobile checkout Condoom Anoniem"><img src="images/nieuws/mobile-ca-checkout.png" width="200" height="181" alt="Mobile checkout Condoom Anoniem" style="float: right;" /></a>Deze test was onderdeel van end-to-end test wat betreft de mobile optie voor <strong>Magento</strong> icm payment provider <strong>Multisafepay</strong>. Standaard is <strong>Magento</strong> niet mobile geoptimaliseerd. Middels een <strong>reponsive magento theme</strong> of optimized dedicated&nbsp;Mobile <strong>"webapp"&nbsp;</strong>(HTML5 high performance optimized theme + RESS) zijn de opties eindeloos.</p>
<p>De oplossing die voor onze klant <strong>Condoom Anoniem</strong> gekozen is, is de <strong>"webapp"</strong> die via hetzelfde domeinnaam beschikbaar is (<a href="http://www.condoom-anoniem.nl/"></a><a href="http://www.condoom-anoniem.nl/">http://www.condoom-anoniem.nl/</a>). Middels browser en device detectie wordt bepaald welke Magento website de klant voorgeschoteld krijgt. Middels deze keuze is het namelijk zeer eenvoudig om in magento de mobile setting te tunen. Denk bijv. aan het uitzetten van <strong>Onestepcheckout</strong> of aanmaken van een custom <strong>Multisafepay</strong> website account.&nbsp;<i><br /></i></p>
<p>De <strong>Magento mobile checkout</strong> van de "webapp" is afgestemd op de gebruiker en kan middels simpele stappen direct zijn order plaatsen. Middels een aangepast reponsive theme layout van Multisafepay komt de gebruiker terecht in een overzichtelijk scherm met de iDeal keuzen van zijn eigen Bank.</p>
<p><a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-ing.png" title="Mobile ING"><img src="images/nieuws/mobile-ing-200.png" width="200" height="300" alt="Mobile ING" /></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-abn-amro.png" title="Mobile ABN AMRO"> <img src="images/nieuws/mobile-abn-amro-200.png" width="200" height="300" alt="Mobile ABN AMRO" /></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-knab.png" title="Mobile KNAB"> <img src="images/nieuws/mobile-knab-200.png" width="200" height="300" alt="Mobile KNAB" /></a><a></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-asn-bank.png" title="Mobile ASN"> <img src="images/nieuws/mobile-asn-bank-200.png" width="200" height="300" alt="Mobile ASN" /></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-friesland-bank.png" title="Mobile Friesland Bank"> <img src="images/nieuws/mobile-friesland-bank-200.png" width="200" height="300" alt="Mobile Friesland Bank" /></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-rabobank.png" title="Mobile Rabobank"> <img src="images/nieuws/mobile-rabobank-200.png" width="200" height="300" alt="Mobile Rabobank" /></a><a></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-sns-bank.png" title="Mobile SNS Bank"> <img src="images/nieuws/mobile-sns-bank-200.png" width="200" height="300" alt="Mobile ABN SNS Bank" /></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-sns-regio-bank.png" title="Mobile SNS Regio Bank"> <img src="images/nieuws/mobile-sns-regio-bank-200.png" width="200" height="300" alt="Mobile SNS Regio Bank" /></a><a></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-triodos-bank.png" title="Mobile Tridios Bank"> <img src="images/nieuws/mobile-triodos-bank-200.png" width="200" height="300" alt="Mobile Tridios Bank" /></a> <a data-lightbox="width:640;height:960;" href="images/nieuws/mobile-van-lanschot-bankiers.png" title="Mobile van Lanschot Bankiers"> <img src="images/nieuws/mobile-van-lanschot-bankiers-200.png" width="200" height="300" alt="Mobile van Lanschot Bankiers" /></a></p>
<p>{snippet meer info}</p>
<p>{snippet raybogman}</p>
